
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 20 23:56:53 EST 2013
//----------------------------------------------------

package fractal.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PENUP = 14;
  public static final int MOD = 28;
  public static final int EXCLAMATION = 30;
  public static final int PLUS = 24;
  public static final int SAVE = 6;
  public static final int RBRACE = 22;
  public static final int RPAREN = 20;
  public static final int HOME = 16;
  public static final int SEMI = 31;
  public static final int ATSYM = 29;
  public static final int CLEAR = 17;
  public static final int END = 10;
  public static final int VARIABLE = 33;
  public static final int LBRACE = 23;
  public static final int LPAREN = 19;
  public static final int RESTORE = 7;
  public static final int RIGHT = 13;
  public static final int RENDER = 3;
  public static final int FORWARD = 11;
  public static final int PENDOWN = 15;
  public static final int COMMA = 21;
  public static final int LEFT = 18;
  public static final int SCALE = 5;
  public static final int EOF = 0;
  public static final int LEVEL = 4;
  public static final int DEF = 8;
  public static final int DIV = 27;
  public static final int MINUS = 25;
  public static final int error = 1;
  public static final int INTEGER = 32;
  public static final int MUL = 26;
  public static final int SELF = 9;
  public static final int FRACTAL = 2;
  public static final int DOUBLE = 34;
  public static final int BACK = 12;
}

